// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

// Valores públicos do projeto Supabase (URL + chave publicável).
// São embutidos no bundle por design e protegidos por RLS. Servem de padrão
// quando o build é gerado sem as variáveis de ambiente (ex.: publicação).
const FALLBACK_SUPABASE_URL = 'https://ccpqkxjgiojbkgooqmpn.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjcHFreGpnaW9qYmtnb29xbXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg0MzYzNTgsImV4cCI6MjEwNDAxMjM1OH0.uO92qnasQGeRkgf4C3BmkqfuLAIGGp5DRSKBDdWrhIE';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

/** Indica se as credenciais públicas do Supabase estão disponíveis neste build. */
export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

const RESOLVED_URL = SUPABASE_URL;
const RESOLVED_KEY = SUPABASE_PUBLISHABLE_KEY;

if (!import.meta.env.VITE_SUPABASE_URL && typeof console !== 'undefined') {
  console.warn('[Supabase] VITE_SUPABASE_URL ausente neste build; usando configuração pública padrão.');
}




function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(RESOLVED_URL, RESOLVED_KEY, {
  global: {
    fetch: createSupabaseFetch(RESOLVED_KEY),
  },
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
